export enum ACTION {
  SIMPLE_PAYMENT = 'simple-payment',
  ADVANCED_PAYMENT = 'advanced-payment',
  BATCH_PAYMENT = 'batch-payment',
  SPLIT_PAYMENT = 'split-payment',
  STAGED_PAYMENT = 'staged-payment',
  STREAMING_PAYMENT = 'streaming-payment',
  CREATE_DECISION = 'create-decision',
  TRANSFER_FUNDS = 'transfer-funds',
  MINT_TOKENS = 'mint-tokens',
  UNLOCK_TOKEN = 'unlock-token',
  MANAGE_TOKENS = 'manage-tokens',
  CREATE_NEW_TEAM = 'create-new-team',
  EDIT_EXISTING_TEAM = 'edit-existing-team',
  MANAGE_REPUTATION = 'manage-reputation',
  MANAGE_PERMISSIONS = 'manage-permissions',
  EDIT_COLONY_DETAILS = 'edit-colony-details',
  UPGRADE_COLONY_VERSION = 'upgrade-colony-version',
  ENTER_RECOVERY_MODE = 'enter-recovery-mode',
  CREATE_NEW_INTEGRATION = 'create-new-integration',
  MANAGE_COLONY_OBJECTIVES = 'manage-colony-objectives',
  USER_PERMISSIONS = 'user-permissions',
  SIMPLE_DISCUSSION = 'simple-discussion',
}

export type Action = (typeof ACTION)[keyof typeof ACTION];
