export enum Icons {
  ArrowRight = 'arrow-right',
  ArrowRotateCCW = 'arrow-rotate-ccw',
  AtSignCircle = 'at-sign-circle',
  CaretDownSmall = 'caret-down-small',
  CaretLeft = 'caret-left',
  CaretRight = 'caret-right',
  CheckMark = 'check-mark',
  /* Used in Checkbox.css */
  CheckMarkPrimary = 'check-mark-primary',
  CircleArrowBack = 'circle-arrow-back',
  CircleBack = 'circle-back',
  CircleClose = 'circle-close',
  CircleMinus = 'circle-minus',
  CirclePerson = 'circle-person',
  CirclePlus = 'circle-plus',
  CircleThumbsDown = 'circle-thumbs-down',
  CircleThumbsUp = 'circle-thumbs-up',
  Close = 'close',
  ColonyLogo = 'colony-logo',
  Comment = 'comment',
  EmojiAlarmLamp = 'emoji-alarm-lamp',
  EmojiBagMoneySign = 'emoji-bag-money-sign',
  EmojiBalance = 'emoji-balance',
  EmojiBuilding = 'emoji-building',
  EmojiCalendar = 'emoji-calendar',
  EmojiClipboard = 'emoji-clipboard',
  EmojiCrane = 'emoji-crane',
  EmojiDna = 'emoji-dna',
  EmojiDollarStack = 'emoji-dollar-stack',
  EmojiEditTools = 'emoji-edit-tools',
  EmojiFirebolt = 'emoji-firebolt',
  EmojiGoblin = 'emoji-goblin',
  EmojiMoneyWings = 'emoji-money-wings',
  EmojiPadlock = 'emoji-padlock',
  EmojiPencilNote = 'emoji-pencil-note',
  EmojiShootingStar = 'emoji-shooting-star',
  EmojiYellowSuperman = 'emoji-yellow-superman',
  File = 'file',
  FilledCircleperson = 'filled-circle-person',
  Lock = 'lock',
  Metamask = 'metamask',
  QustionMarkInverted = 'question-mark-inverted',
  QuestionMark = 'question-mark',
  ReturnArrow = 'return-arrow',
  Search = 'search',
  Settings = 'settings',
  Star = 'star',
  ThreeDotsRow = 'three-dots-row',
  Trash = 'trash',
  TriangleWarning = 'triangle-warning',
  UserPlus = 'user-plus',
  Wallet = 'wallet',
}

export enum MultiColorIcons {
  CircleCheckPrimary = 'circle-check-primary',
  Metamask = 'metamask',
  ShieldPink = 'shield-pink',
}
