import {
  POLYGON_NETWORK,
  AMOY_NETWORK,
  GANACHE_NETWORK_1,
  GANACHE_NETWORK_2,
  type NetworkInfo,
} from '~constants';

export const SUPPORTED_CHAINS: NetworkInfo[] = [
  POLYGON_NETWORK,
  AMOY_NETWORK,
  GANACHE_NETWORK_1,
  GANACHE_NETWORK_2,
];
