name: colony-cdapp-on-demand-env
services:
  amplify-setup:
    extends:
      file: colony-cdapp-dev-env-orchestration.yaml
      service: amplify-setup

  network-contracts:
    extends:
      file: colony-cdapp-dev-env-orchestration.yaml
      service: network-contracts
    environment:
      ARCHIVE_RPC: ${ARCHIVE_RPC}
      FORKED_NETWORK_ADDRESS: ${FORKED_NETWORK_ADDRESS}
      LATEST_STATE_URL: ${LATEST_STATE_URL}

  reputation-monitor:
    extends:
      file: colony-cdapp-dev-env-orchestration.yaml
      service: reputation-monitor

  mocking:
    extends:
      file: colony-cdapp-dev-env-orchestration.yaml
      service: mocking

  block-ingestor:
    extends:
      file: colony-cdapp-dev-env-orchestration.yaml
      service: block-ingestor
    depends_on:
      clone-dynamodb-data:
        condition: service_completed_successfully

  amplify:
    extends:
      file: colony-cdapp-dev-env-orchestration.yaml
      service: amplify

  clone-dynamodb-data:
    container_name: 'clone-dynamodb-data'
    image: colony-cdapp-dev-env/clone-dynamodb-data:latest
    depends_on:
      amplify:
        condition: service_healthy
    tty: true
    environment:
      LOCAL_ENDPOINT_URL: http://amplify:62224
      ENV_NAME: ${ENV_NAME}
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}

  auth-proxy:
    extends:
      file: colony-cdapp-dev-env-orchestration.yaml
      service: auth-proxy

  network-files:
    extends:
      file: colony-cdapp-dev-env-orchestration.yaml
      service: network-files

volumes:
  amplify-backend:
  amplify-mock-data:
