import { Id } from '@colony/colony-js';
import React from 'react';
import { defineMessage, FormattedMessage } from 'react-intl';

import { getMainClasses } from '~utils/css';
import ExternalLink from '~shared/ExternalLink';
import { MD_REPUTATION_INFO } from '~constants/externalUrls';

import styles from './NotEnoughReputation.css';

interface Appearance {
  marginTop?: 'negative';
}

interface Props {
  domainId?: number;
  appearance?: Appearance;
  includeForceCopy?: boolean;
}

const displayName = 'NotEnoughReputation';

const MSG = defineMessage({
  title: {
    id: `${displayName}.title`,
    defaultMessage: `There is no reputation in this {onRootDomain, select,
      true {colony}
      other {team}
    } yet.`,
  },
  description: {
    id: `${displayName}.description`,
    defaultMessage: `Reputation is generated by making payments
    to members with this colony’s native token.{includeForceCopy, select,
     true { If you have the necessary permissions to
     take this action you can toggle “Force”
     in the top right to bypass the governance process.}
     other {}
     } <a>Learn more</a>`,
  },
});

const NoReputationInfoLink = (chunks: React.ReactNode[]) => (
  <ExternalLink href={MD_REPUTATION_INFO}>{chunks}</ExternalLink>
);

const NotEnoughReputation = ({
  domainId = Id.RootDomain,
  appearance,
  includeForceCopy = true,
}: Props) => (
  <div className={`${styles.container} ${getMainClasses(appearance, styles)}`}>
    <p className={styles.title}>
      <FormattedMessage
        {...MSG.title}
        values={{ onRootDomain: domainId === Id.RootDomain }}
      />
    </p>
    <p className={styles.text}>
      <FormattedMessage
        {...MSG.description}
        values={{
          a: NoReputationInfoLink,
          includeForceCopy,
        }}
      />
    </p>
  </div>
);

NotEnoughReputation.displayName = displayName;

export default NotEnoughReputation;
